---
server:
  port: 9000
  contextPath: /ClinicalData
---
spring:
  profiles: local, default
  http:
    multipart:
      max-file-size: 2KB
      max-request-size: 2KB
datasource:
  clinicaldata:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
  http:
    multipart:
      max-file-size: 2KB
      max-request-size: 2KB
datasource:
  clinicaldata:
    url: jdbc:mysql://localhost:3306/websystique
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect